import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'Data.dart';
import 'package:http/http.dart' as http;

class ScendScreen extends StatefulWidget {
  ScendScreen({Key key}) : super(key: key);

  @override
  Second_Screen createState() => Second_Screen();
}

class Second_Screen extends State<ScendScreen> {

  Future<Autogenerated> future;

  @override
  void initState() {
    super.initState();
    future = getData() as Future<Autogenerated>;
  }

  Autogenerated dataModel = Autogenerated();

  Future<Autogenerated> getData() async {
    /// Server LockUp - Get Response from it
    try {
      final response = await http
          .get(Uri.parse('https://retail.amit-learning.com/api/categories'));

      dataModel = Autogenerated.fromJson(jsonDecode(response.body));
      print('data model: ${jsonDecode(response.body)}');
      return dataModel;
    } catch (error) {
      throw Exception('Failed to load data');
    }
  }

  @override
  Widget build(BuildContext context) {
    String data='screen Argument';
    return Scaffold(
      appBar: AppBar(

        title: Text('First App'),
        backgroundColor: Colors.red[800],
      ),
      body: FutureBuilder(
          future: future,
          builder: (context, snapshot) {
            switch (snapshot.connectionState) {
              case ConnectionState.waiting:
                return Center(child: CircularProgressIndicator());
              default:
                if (snapshot.hasError) {
                  print(snapshot.error);
                  return Center(child: Text('Data Not Found'));
                } else
                  return GridView.builder(
                      gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                          maxCrossAxisExtent: 200,
                          childAspectRatio: 3 / 2,
                          crossAxisSpacing: 20,
                          mainAxisSpacing: 20),
                      itemCount: dataModel.categories.length,
                      itemBuilder: (BuildContext ctx, index) {
                        return InkWell(
                          onTap: (){},
                          // child: Padding(
                          //   padding: EdgeInsets.all(12.0),
                            child: Container(
                              alignment: Alignment.center,
                              child: Text(dataModel.categories[index].name,
                                style: TextStyle(color: Colors.black,
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                    backgroundColor: Colors.grey
                                ),
                              ),

                              decoration: BoxDecoration(
                                  color: Colors.amber,
                                  borderRadius: BorderRadius.circular(15),
                                  image: DecorationImage(
                                    fit: BoxFit.cover,
                                    image: NetworkImage(dataModel.categories[index].avatar),
                                  )
                              ),
                            ),
                         // ),
                        );
                      });
            }
          }),
    );
  }
}